version: '3.9'
services:
  ml-model:
    build: .
    ports:
      - "5000:5000"
    environment:
      MODEL_WEIGHTS_PATH: "/app/src/weights/model_weights.pt"
    volumes:
      - ./src:/app/src
    command: ["python", "src/app.py"]

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      # Mount the Prometheus config from the infra directory
      - ./infra/k8s/prometheus-grafana/prometheus-config.yaml:/etc/prometheus/prometheus-config.yaml
      # We need to rename the config file inside container to prometheus.yml
      # We'll do that by using a command that copies the file at runtime
    command: /bin/sh -c "cp /etc/prometheus/prometheus-config.yaml /etc/prometheus/prometheus.yml && prometheus --config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SECURITY_ADMIN_USER: admin
    # No special volumes needed out of the box, but you could map dashboards like:
    # volumes:
    #   - ./infra/k8s/prometheus-grafana/dashboards:/var/lib/grafana/dashboards
    # If you want to pre-provision data sources and dashboards, you can mount them here
